Repository Yothu/Yu-Gi-Oh--Card-Data-Base, pull requests merged in 2022-02, with the labels that each got.

#37 Show amount of cards displayed, on navbar
  dist/displayList.bundle.js
  dist/index.bundle.js
  dist/index.html
  src/countCards.js
  src/displayList.js
  src/index.html
  src/style.css
Labels: enhancement

#40 Feature/add card counter test
  dist/displayList.bundle.js
  dist/index.bundle.js
  src/__tests__/countCards.test.js
  src/__tests__/updateCardCounter.test.js
  src/countCards.js
  src/displayList.js
  src/updateCardCounter.js
Labels: test

#43 Fill out readme
  README.md
  app_screenshot.png
  package-lock.json
  package.json
  src/__tests__/commentCounter.test.js
Labels: documentation

#45 Javascript API Capstone Project
  .babelrc
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .hintrc
  .stylelintrc.json
  README.md
  app_screenshot.png
  dist/246a7394d118ab678e64.ttf
  dist/5829a23eb824269a2c98.ttf
  dist/af1be6065f1c705a76a2.png
  dist/c9783c59559ac87350c1.ttf
  dist/dcc701aeeb7b301b1bc0.ttf
  dist/displayComment.bundle.js
  dist/displayList.bundle.js
  dist/getCardList.bundle.js
  dist/getComments.bundle.js
  dist/index.bundle.js
  dist/index.html
  dist/loadImage.bundle.js
  dist/runtime.bundle.js
  dist/shared.bundle.js
  package-lock.json
  package.json
  src/__tests__/commentCounter.test.js
  src/__tests__/countCards.test.js
  src/__tests__/updateCardCounter.test.js
  src/apiCode.js
  src/cardLikes.js
  src/checkCommentData.js
  src/commentCounter.js
  src/components/fonts/hinted-subset-Matrix-Book.ttf
  src/components/fonts/hinted-subset-MatrixRegularSmallCaps.ttf
  src/components/fonts/hinted-subset-StoneSerifLT-Italic.ttf
  src/components/fonts/hinted-subset-Yu-Gi-OhITCStoneSerifBoldSmallCaps.ttf
  src/components/images/monster-cards-logo.png
  src/countCards.js
  src/createComment.js
  src/deleteComments.js
  src/displayCommentPopup.js
  src/displayCommentsOnPopup.js
  src/displayList.js
  src/font-style.css
  src/getCardsApiData.js
  src/getComments.js
  src/index.html
  src/index.js
  src/load-image-module.js
  src/style.css
  src/updateCardCounter.js
  webpack.config.js
  yarn.lock
Labels: enhancement

#46 Add author and image metadata
  app_screenshot.png
  src/index.html
Labels: documentation
